name: testod
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.1
  get: ^4.6.6
  camera: ^0.10.5+9
  image: ^3.3.0
  speech_to_text: ^6.6.2
  tflite_flutter: ^0.9.5
  tflite_flutter_helper_plus: ^0.0.2
  flutter_tflite: ^1.0.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/model.tflite
    - assets/labels.txt
    - assets/yolov2_tiny.tflite
    - assets/yolov5s.tflite
